"""
Django settings for Annu project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from urllib.parse import urlparse

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-l#2q(95krxuw2&xs^kyisi^trp3kw80$dtr_13nv43ew%=hq+z',
)

ENABLE_PROMETHEUS = os.environ.get('ENABLE_PROMETHEUS', '').lower() in ('1', 'true', 'yes')

_is_render = bool(os.environ.get('RENDER'))
_is_docker = os.environ.get('DOCKER', '').lower() in ('1', 'true', 'yes')
_public_tunnel_demo = os.environ.get('PUBLIC_TUNNEL_DEMO', '').lower() in ('1', 'true', 'yes')
_default_debug = 'False' if _is_render else 'True'
DEBUG = os.environ.get('DEBUG', _default_debug).lower() in ('true', '1', 'yes')
if _public_tunnel_demo:
    DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']
_render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if _render_host:
    ALLOWED_HOSTS.append(_render_host)
if _is_render:
    # Correct absolute URLs and host validation behind Render's proxy
    USE_X_FORWARDED_HOST = True
if _is_docker:
    USE_X_FORWARDED_HOST = True
    for _h in ('web', 'nginx'):
        if _h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_h)
_extra_hosts = os.environ.get('ALLOWED_HOSTS', '')
if _extra_hosts:
    ALLOWED_HOSTS.extend(h.strip() for h in _extra_hosts.split(',') if h.strip())

if _public_tunnel_demo:
    print(
        'PUBLIC_TUNNEL_DEMO=1: using ALLOWED_HOSTS=* and HTTPS proxy headers for Cloudflare TryCloudflare. '
        'Demo only — do not expose real data.',
        file=sys.stderr,
    )
    ALLOWED_HOSTS = ['*']
    USE_X_FORWARDED_HOST = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

INSTALLED_APPS = []
if ENABLE_PROMETHEUS:
    INSTALLED_APPS.append('django_prometheus')
INSTALLED_APPS += [
    'adminlte3',
    'adminlte3_theme',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'app',
    'ckeditor',
    'cart',
    'api',
]

CART_SESSION_ID = 'cart'

_BASE_MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MIDDLEWARE = (
    ['django_prometheus.middleware.PrometheusBeforeMiddleware']
    + _BASE_MIDDLEWARE
    + ['django_prometheus.middleware.PrometheusAfterMiddleware']
    if ENABLE_PROMETHEUS
    else _BASE_MIDDLEWARE
)

RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', 'rzp_test_fZDP5mwWKWM2ZE')
RAZORPAY_KEY_SECRATE = os.environ.get('RAZORPAY_KEY_SECRET', 'hv2ZZW9luTRGE91vxQZdyPEV')

ROOT_URLCONF = 'Annu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['Template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart_total_amount',
                'Annu.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'Annu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

def _postgres_url_looks_valid(url: str) -> bool:
    """Reject truncated DATABASE_URL values (common copy/paste mistake on Render)."""
    try:
        parsed = urlparse(url)
        if parsed.scheme not in ('postgres', 'postgresql'):
            return True
        host = parsed.hostname or ''
        if not host:
            return False
        # Docker Compose uses single-label service names (e.g. db).
        if '.' not in host:
            return _is_docker
        return True
    except Exception:
        return False


_raw_db_url = (os.environ.get('DATABASE_URL') or '').strip()
_use_postgres = bool(_raw_db_url) and _postgres_url_looks_valid(_raw_db_url)

if _raw_db_url and not _use_postgres and not _is_docker:
    print(
        'WARNING: DATABASE_URL is set but invalid or truncated (hostname must include a domain). '
        'Falling back to SQLite. Fix DATABASE_URL in the Render dashboard to use Postgres.',
        file=sys.stderr,
    )

if _use_postgres:
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=os.environ.get('DATABASE_SSL_REQUIRE', 'True').lower()
            in ('true', '1', 'yes'),
        ),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


EMAIL_USE_TLS = True
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'webmaster@localhost')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# HTTP behind Nginx in Docker (no TLS) — avoid secure-only cookies breaking login/forms.
if _is_docker and os.environ.get('DOCKER_BEHIND_HTTP', '1').lower() in ('1', 'true', 'yes'):
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False

_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(',') if o.strip()]
if _render_host:
    for _origin in (f'https://{_render_host}', f'http://{_render_host}'):
        if _origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_origin)

if _is_docker:
    for _origin in (
        'http://localhost',
        'http://127.0.0.1',
        'http://localhost:8080',
        'http://127.0.0.1:8080',
        'http://nginx',
        'http://web:8000',
    ):
        if _origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_origin)

if os.environ.get('DOCKER_JSON_LOGS', '').lower() in ('1', 'true', 'yes'):
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'jsonish': {
                'format': '{"level":"%(levelname)s","time":"%(asctime)s","logger":"%(name)s","message":"%(message)s"}',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'jsonish',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': os.environ.get('LOG_LEVEL', 'INFO'),
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': os.environ.get('LOG_LEVEL', 'INFO'),
                'propagate': False,
            },
        },
    }
