services:
  - type: web
    name: django-ecommerce
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Annu.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "2"
